CREATE USER 'app'@'localhost' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON store.* TO 'app'@'localhost';
FLUSH PRIVILEGES;

SELECT * FROM vendas;

SET SQL_SAFE_UPDATES = 0;
DELETE FROM vendas;
SET SQL_SAFE_UPDATES = 1;

DELETE FROM nome_da_tabela
WHERE id = 21;


SELECT * FROM vendas;
SELECT COUNT(*) FROM vendas;

TRUNCATE TABLE vendas;
